title: Katy Rotman
description: Senior Software Developer & Tech Lead
logo: # Leave this empty for now or add path to an image
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
